### ISSUE TITLE
OVM can't locate me by GPS

### ISSUE THREAD

**Issue by nicolasmaia** [Rudloff/openvegemap-cordova#5]
When I click on 'Locate me', nothing happens.

I don't think it's a problem on my end because other map apps like Maps.me, StreetComplete and Transportr can find me easily.

**Comment by Rudloff** [comment]
Hum, I can't reproduce this.

(Note that currently it only moves the map to where you are but does not display any marker on your position.)

If you are using Android >=6 , can you check if the app has the Location permission enabled?
Do you know how to use [logcat](https://developer.android.com/studio/command-line/logcat)? If so, can you check if you get any location-related error?

**Comment by nicolasmaia** [comment]
Oddly, OVM doesn't even ask for the Location permission (Android 7.0). Doesn't move either.

I don't know how to use logcat but I'll take a look at it, thanks.

Just wanted to say it's awesome you released this as it means I can finally break free from HappyCow :)

**Comment by Rudloff** [comment]
It definitely should ask for your permission when you first press the *Locate me* menu item. But it is hard to tell what goes wrong without any logs.

(I recently updated the geolocation library (7e5a08bcf06a6540cb5afb8d70e34aa86f85b11a) so maybe the next release will fix this for you.)

**Comment by Rudloff** [comment]
I published a new 0.7.1 release with an updated geolocation library. Can you check if it fixes your issue?

**Comment by nicolasmaia** [comment]
Thanks! So, it doesn't fix it. No difference.

For reference, in the meantime I switched the system from MIUI to LineageOS 14.1 (and now on 15.1). This issue persisted through all those changes. All other apps seem to have location working as intended.

Interestingly, when I open http://openvegemap.netlib.re/ on my phone, it can fetch my location.

**Comment by Rudloff** [comment]
Hum, that's quite strange.
Did you try manually granting the geolocation permission to the app? (See *Turn permissions on or off* [here](https://support.google.com/googleplay/answer/6270602?hl=en)).

**Comment by nicolasmaia** [comment]
I just checked, OpenVegeMap has geolocation permissions. What's weird is that it doesn't even ask to use it.

**Comment by Rudloff** [comment]
Then I'm afraid I won't be able to fix this unless you can provide an error message (with logcat).

**Comment by Rudloff** [comment]
@picsi Did you have a look at logcat?

Also, what location provider did you enable (GPS, wifi or both)? Can you try with different settings?

**Comment by nicolasmaia** [comment]
I did not, I need some time to learn about logcat and how it works.

I was trying with GPS only. I tried allowing GPS+Wifi but that had no effect.

**Comment by picsi** [comment]
I did not, I need some time to learn about logcat and how it works.

I was trying with GPS only. I tried allowing GPS+Wifi but that had no effect.

**Comment by nicolasmaia** [comment]
I had uninstalled it months ago and reinstalled it today.

This problem no longer happens now.
